name: Upload Novel

on:
  workflow_dispatch: # Menjalankan workflow secara manual
  push:
    branches:
      - main

jobs:
  upload_novel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload novel
        run: |
          # Ambil input dari file atau variabel (misalnya dari formulir HTML)
          # Misalkan kita sudah mengumpulkan input seperti nama novel dan kontennya
          NOVEL_NAME="novel-example.md"
          NOVEL_CONTENT="Isi novel di sini..."

          # Encode konten menjadi base64
          BASE64_CONTENT=$(echo -n "$NOVEL_CONTENT" | base64)

          # Membuat file JSON untuk API GitHub
          curl -X PUT \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "{\"message\": \"Upload novel baru: $NOVEL_NAME\", \"content\": \"$BASE64_CONTENT\"}" \
               "https://api.github.com/repos/${{ github.repository }}/contents/novels/$NOVEL_NAME"
          
      - name: Display successful upload message
        run: echo "Novel uploaded successfully!"
