name: Get Novels

on:
  workflow_dispatch: # Menjalankan workflow secara manual
  push:
    branches:
      - main

jobs:
  fetch_novels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get list of novels
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -X GET \
               "https://api.github.com/repos/${{ github.repository }}/contents/novels" > novels.json
          
      - name: Display results
        run: |
          cat novels.json
